<section class="page-title"><div><p class="eyebrow">DÉCOUVRIR</p><h1>Catalogue des formations</h1><p>Développez vos compétences avec les parcours <?= htmlspecialchars($brand['name']??'IFMAP') ?>.</p></div></section>
<div class="filter-chips"><button class="active">Toutes</button><button>Présentiel</button><button>En ligne</button><button>Mixte</button></div>
<div class="course-grid catalog-grid">
<?php foreach($courses as $course): $url='/formations/'.rawurlencode($course['slug']); ?>
<article class="course-card modern-student-course"><a class="course-cover <?= htmlspecialchars($course['color']) ?>" href="<?= htmlspecialchars($url) ?>"><span class="course-cat"><?= htmlspecialchars($course['category']) ?></span><?php if(!empty($course['thumbnail'])): ?><img src="<?= htmlspecialchars($course['thumbnail']) ?>" alt="<?= htmlspecialchars($course['title']) ?>"><?php else: ?><i data-icon="book"></i><?php endif ?></a><div class="course-body"><h3><?= htmlspecialchars($course['title']) ?></h3><p>Par <?= htmlspecialchars($course['teacher']) ?></p><div class="course-meta"><span><i data-icon="play"></i><?= (int)$course['lessons'] ?> leçons</span><span><i data-icon="clock"></i><?= htmlspecialchars($course['duration']) ?></span></div><div class="course-card-actions"><?php if($course['enrolled']): ?><a href="/academie/formation?course=<?= (int)$course['id'] ?>" class="btn secondary">Ouvrir</a><?php else: ?><a href="<?= htmlspecialchars($url) ?>" class="btn primary">Découvrir</a><?php endif ?><button type="button" class="btn secondary share-course" data-share-url="<?= htmlspecialchars($url) ?>" data-share-title="<?= htmlspecialchars($course['title']) ?>">↗ Partager</button></div></div></article>
<?php endforeach ?>
</div>
<style>.modern-student-course{overflow:hidden;transition:transform .2s,box-shadow .2s}.modern-student-course:hover{transform:translateY(-4px);box-shadow:0 18px 45px #172f2815}.modern-student-course .course-cover{overflow:hidden;padding:0;display:block;position:relative}.modern-student-course .course-cover img{width:100%;height:100%;object-fit:cover;display:block}.modern-student-course .course-cat{position:absolute;z-index:1;top:14px;left:14px;background:#fff;color:#173b35;padding:6px 10px;border-radius:99px;box-shadow:0 5px 15px #0002}.course-card-actions{display:grid;grid-template-columns:1fr auto;gap:8px;margin-top:14px}.course-card-actions .btn{margin:0}.share-course{white-space:nowrap}</style>
<script>document.querySelectorAll('.share-course').forEach(button=>button.addEventListener('click',async()=>{const url=new URL(button.dataset.shareUrl,location.origin).href;const data={title:button.dataset.shareTitle,text:'Découvrez cette formation',url};if(navigator.share){try{await navigator.share(data)}catch(e){}}else{await navigator.clipboard.writeText(url);const old=button.textContent;button.textContent='✓ Lien copié';setTimeout(()=>button.textContent=old,1800)}}));</script>
