<section class="welcome"><div><p class="eyebrow">VENDREDI 28 AOÛT</p><h1>Bonjour Assa <span>👋🏾</span></h1><p>Continuez sur votre lancée. Vous avez complété <strong>4 leçons</strong> cette semaine.</p></div><div class="streak"><span>🔥</span><div><strong>7 jours</strong><small>Série en cours</small></div></div></section>
<section class="stats-grid">
<article><span class="stat-icon purple"><i data-icon="book"></i></span><div><small>FORMATIONS EN COURS</small><strong>3</strong><em>sur 5 inscrites</em></div></article>
<article><span class="stat-icon green"><i data-icon="clock"></i></span><div><small>TEMPS D'APPRENTISSAGE</small><strong>24h 30</strong><em>+ 3h cette semaine</em></div></article>
<article><span class="stat-icon orange"><i data-icon="award"></i></span><div><small>CERTIFICATS OBTENUS</small><strong><?= (int)$certificateCount ?></strong><em><a href="/academie/certificats">Voir mes certificats →</a></em></div></article>
<article><span class="stat-icon blue"><i data-icon="target"></i></span><div><small>PROGRESSION MOYENNE</small><strong>68%</strong><em>Très bon rythme !</em></div></article>
</section>
<?php $enrolledCourses=array_values(array_filter($courses,fn($item)=>$item['enrolled']));$resume=$enrolledCourses[0]??null;$_SESSION['my_course_count']=count($enrolledCourses); ?>
<div class="section-head"><div><h2>Reprendre ma formation</h2><p>Continuez là où vous vous êtes arrêté</p></div><a href="/cours">Voir toutes mes formations →</a></div>
<?php if($resume): ?><article class="continue-card"><div class="course-art <?= htmlspecialchars($resume['color']) ?>"><span>IF</span><small><?= htmlspecialchars(strtoupper($resume['category'])) ?></small></div><div class="continue-copy"><span class="pill"><?= $resume['progress']?'EN COURS':'À COMMENCER' ?></span><h2><?= htmlspecialchars($resume['title']) ?></h2><p>Par <?= htmlspecialchars($resume['teacher']) ?></p><div class="progress-row"><div class="progress"><span style="width:<?= (int)$resume['progress'] ?>%"></span></div><strong><?= (int)$resume['progress'] ?>%</strong></div><small><?= (int)$resume['lessons'] ?> leçon(s) dans ce parcours</small></div><a class="btn primary" href="/academie/formation?course=<?= (int)$resume['id'] ?>"><?= $resume['progress']?'Continuer':'Commencer' ?> <span>→</span></a></article><?php else: ?><div class="panel admin-empty">Vous n’avez aucune formation active. <a href="/formations">Découvrir le catalogue</a></div><?php endif ?>
<div class="section-head compact"><div><h2>Mes formations en cours</h2><p>Progressez à votre rythme</p></div><a href="/catalogue">Explorer le catalogue →</a></div>
<div class="course-grid"><?php foreach ($enrolledCourses as $course): ?><article class="course-card"><a href="/academie/formation?course=<?= (int)$course['id'] ?>"><div class="course-cover <?= htmlspecialchars($course['color']) ?>"><span class="course-cat"><?= htmlspecialchars($course['category']) ?></span><i data-icon="<?= $course['icon'] ?>"></i></div><div class="course-body"><h3><?= htmlspecialchars($course['title']) ?></h3><p>Par <?= htmlspecialchars($course['teacher']) ?></p><div class="progress-row"><div class="progress"><span style="width:<?= (int)$course['progress'] ?>%"></span></div><strong><?= (int)$course['progress'] ?>%</strong></div><div class="course-meta"><span><i data-icon="play"></i><?= (int)$course['lessons'] ?> leçons</span><span><i data-icon="clock"></i><?= htmlspecialchars($course['duration']) ?></span></div></div></a></article><?php endforeach ?></div>

<?php if (($user['role'] ?? '') === 'instructor'): ?>
<div class="section-head compact" id="mes-cours-formateur"><div><h2>Mes cours comme formateur</h2><p>Les formations que l’administration vous a attribuées</p></div></div>
<div class="instructor-course-grid"><?php foreach ($instructorCourses as $course): ?><article class="panel instructor-course"><div><span class="pill"><?= $course['status']==='published'?'PUBLIÉ':'BROUILLON' ?></span><h3><?= htmlspecialchars($course['title']) ?></h3><p><?= (int)$course['modules'] ?> section(s) · <?= (int)$course['lessons'] ?> leçon(s) · <?= (int)$course['learners'] ?> apprenant(s)</p></div><a class="btn secondary" href="/academie/formation?course=<?= (int)$course['id'] ?>">Voir le cours</a></article><?php endforeach ?><?php if(!$instructorCourses): ?><div class="panel profile-empty">Aucun cours ne vous est encore attribué. L’administrateur peut vous sélectionner dans la fiche d’une formation.</div><?php endif ?></div>
<?php endif ?>

<?php $initials=strtoupper(substr($user['name']??'U',0,1)); ?>
<section id="profil" class="dashboard-profile">
<div class="section-head compact"><div><h2>Profil et préférences</h2><p>Photo, informations personnelles, CV et présentation formateur</p></div></div>
<?php if($flash): ?><div class="toast">✓ <?= htmlspecialchars($flash) ?></div><?php endif ?>
<?php if($error): ?><div class="profile-error">! <?= htmlspecialchars($error) ?></div><?php endif ?>
<div class="profile-dashboard-grid">
<form class="panel profile-dashboard-card" method="post" action="/profil" enctype="multipart/form-data">
<div class="profile-dropzone avatar-dropzone" data-dropzone="avatar" tabindex="0"><div class="profile-photo"><?php if(!empty($user['avatar'])): ?><img id="avatar-preview" src="<?= htmlspecialchars($user['avatar']) ?>" alt="Photo de profil"><?php else: ?><span id="avatar-initials"><?= htmlspecialchars($initials) ?></span><img id="avatar-preview" hidden alt="Aperçu"><?php endif ?></div><div><strong>Déposez votre photo ici</strong><small>ou cliquez pour sélectionner · JPG, PNG ou WebP · 5 Mo maximum</small><span class="drop-file-name" data-file-name="avatar">Aucun nouveau fichier</span></div><input type="file" name="avatar" accept="image/jpeg,image/png,image/webp" data-avatar-input hidden></div>
<div class="profile-fields"><label>Nom complet<input name="name" value="<?= htmlspecialchars($user['name']??'') ?>" required></label><label>Email<input type="email" value="<?= htmlspecialchars($user['email']??'') ?>" disabled></label><label>Téléphone<input name="phone" value="<?= htmlspecialchars($user['phone']??'') ?>"></label><?php if(($user['role']??'')!=='admin'): ?><label>Statut du compte<select name="role"><option value="learner" <?= ($user['role']??'learner')==='learner'?'selected':'' ?>>Apprenant</option><option value="instructor" <?= ($user['role']??'')==='instructor'?'selected':'' ?>>Formateur / enseignant</option></select></label><?php endif ?><label class="full">Spécialité du formateur<input name="specialty" value="<?= htmlspecialchars($user['specialty']??'') ?>" placeholder="Ex. Gestion de station-service"></label><label class="full">Biographie professionnelle<textarea name="bio" rows="5" placeholder="Expérience, expertise et méthode pédagogique"><?= htmlspecialchars($user['bio']??'') ?></textarea></label><div class="full profile-dropzone cv-dropzone" data-dropzone="cv" tabindex="0"><span class="drop-icon">⇧</span><div><strong>Déposez votre CV ici</strong><small>PDF, DOC ou DOCX · 10 Mo maximum</small><span class="drop-file-name" data-file-name="cv"><?= !empty($user['cv_path'])?'Un CV est déjà enregistré':'Aucun fichier sélectionné' ?></span><?php if(!empty($user['cv_path'])): ?><a href="<?= htmlspecialchars($user['cv_path']) ?>" target="_blank" rel="noopener">Voir le CV actuel</a><?php endif ?></div><input type="file" name="cv" accept="application/pdf,.doc,.docx" data-cv-input hidden></div></div>
<p class="profile-note">Lorsque le statut « Formateur » est sélectionné et qu’un cours vous est attribué, votre photo, spécialité, biographie et CV apparaissent automatiquement dans l’onglet « Formateur » de ce cours.</p><button class="btn primary">Enregistrer mon profil</button>
</form>
<form class="panel profile-dashboard-card security-card" method="post" action="/profil/mot-de-passe"><h3>Sécurité et session</h3><p>Modifiez votre mot de passe ou fermez votre session.</p><label>Mot de passe actuel<input type="password" name="current_password" required></label><label>Nouveau mot de passe<input type="password" name="password" minlength="8" required></label><label>Confirmation<input type="password" name="password_confirmation" minlength="8" required></label><button class="btn secondary">Modifier le mot de passe</button><hr><button class="btn profile-logout" type="submit" formaction="/deconnexion" formnovalidate>↪ Se déconnecter de mon compte</button></form>
</div></section>
<style>.dashboard-profile{scroll-margin-top:95px}.profile-dashboard-grid{display:grid;grid-template-columns:minmax(0,2fr) minmax(260px,1fr);gap:18px}.profile-dashboard-card{padding:24px}.avatar-editor{display:flex;align-items:center;gap:16px;margin-bottom:24px}.avatar-editor>div:last-child{display:flex;flex-direction:column;align-items:flex-start;gap:7px}.profile-photo{width:82px;height:82px;border-radius:50%;overflow:hidden;display:grid;place-items:center;background:color-mix(in srgb,var(--primary) 12%,white);color:var(--primary);font-size:25px;font-weight:800}.profile-photo img{width:100%;height:100%;object-fit:cover}.profile-fields{display:grid;grid-template-columns:1fr 1fr;gap:15px}.profile-dashboard-card label{display:flex;flex-direction:column;gap:7px;font-size:11px;font-weight:700}.profile-dashboard-card input,.profile-dashboard-card select,.profile-dashboard-card textarea{border:1px solid var(--line);border-radius:9px;padding:11px;background:#fff;font:inherit}.profile-dashboard-card textarea{resize:vertical}.profile-fields .full{grid-column:1/-1}.profile-fields a{color:var(--primary);margin-top:5px}.profile-note{padding:12px;background:color-mix(in srgb,var(--primary) 7%,white);border-radius:9px;color:var(--muted);font-size:11px;line-height:1.6}.security-card{align-self:start;display:flex;flex-direction:column;gap:14px}.instructor-course-grid{display:grid;gap:12px}.instructor-course{padding:18px;display:flex;align-items:center;justify-content:space-between}.instructor-course h3{margin:8px 0 4px}.instructor-course p,.profile-empty{color:var(--muted)}.profile-empty{padding:22px}.profile-error{padding:12px;margin-bottom:15px;border-radius:9px;background:#fde8e3;color:#a53d31}@media(max-width:850px){.profile-dashboard-grid{grid-template-columns:1fr}.profile-fields{grid-template-columns:1fr}.profile-fields .full{grid-column:1}}</style>
