<section class="welcome"><div><p class="eyebrow">VENDREDI 28 AOÛT</p><h1>Bonjour Assa <span>👋🏾</span></h1><p>Continuez sur votre lancée. Vous avez complété <strong>4 leçons</strong> cette semaine.</p></div><div class="streak"><span>🔥</span><div><strong>7 jours</strong><small>Série en cours</small></div></div></section>
<section class="stats-grid">
<article><span class="stat-icon purple"><i data-icon="book"></i></span><div><small>FORMATIONS EN COURS</small><strong>3</strong><em>sur 5 inscrites</em></div></article>
<article><span class="stat-icon green"><i data-icon="clock"></i></span><div><small>TEMPS D'APPRENTISSAGE</small><strong>24h 30</strong><em>+ 3h cette semaine</em></div></article>
<article><span class="stat-icon orange"><i data-icon="award"></i></span><div><small>CERTIFICATS OBTENUS</small><strong>2</strong><em>Voir mes certificats →</em></div></article>
<article><span class="stat-icon blue"><i data-icon="target"></i></span><div><small>PROGRESSION MOYENNE</small><strong>68%</strong><em>Très bon rythme !</em></div></article>
</section>
<div class="section-head"><div><h2>Reprendre ma formation</h2><p>Continuez là où vous vous êtes arrêté</p></div><a href="/cours">Voir toutes mes formations →</a></div>
<article class="continue-card"><div class="course-art indigo"><span>PMP</span><small>MANAGEMENT PUBLIC</small></div><div class="continue-copy"><span class="pill">EN COURS</span><h2>Pilotage de la performance publique</h2><p>Module 3 · Indicateurs et tableaux de bord</p><div class="progress-row"><div class="progress"><span style="width:72%"></span></div><strong>72%</strong></div><small>17 leçons terminées sur 24</small></div><a class="btn primary" href="/cours">Continuer le cours <span>→</span></a></article>
<div class="section-head compact"><div><h2>Mes formations en cours</h2><p>Progressez à votre rythme</p></div><a href="/catalogue">Explorer le catalogue →</a></div>
<div class="course-grid"><?php foreach ($courses as $course): ?><article class="course-card"><div class="course-cover <?= $course['color'] ?>"><span class="course-cat"><?= htmlspecialchars($course['category']) ?></span><i data-icon="<?= $course['icon'] ?>"></i></div><div class="course-body"><h3><?= htmlspecialchars($course['title']) ?></h3><p>Par <?= htmlspecialchars($course['teacher']) ?></p><div class="progress-row"><div class="progress"><span style="width:<?= $course['progress'] ?>%"></span></div><strong><?= $course['progress'] ?>%</strong></div><div class="course-meta"><span><i data-icon="play"></i><?= $course['lessons'] ?> leçons</span><span><i data-icon="clock"></i><?= $course['duration'] ?></span></div></div></article><?php endforeach ?></div>

