<section class="admin-welcome"><div><p class="eyebrow">IDENTITÉ GLOBALE</p><h1>Branding et documents</h1><p>Le logo, le favicon, la signature et les couleurs alimentent toutes les interfaces et tous les documents officiels.</p></div><button class="btn secondary" data-reset-brand>Réinitialiser les couleurs</button></section>
<form class="branding-grid" method="post" action="/admin/branding" enctype="multipart/form-data">
<div>
<section class="panel form-panel"><div class="panel-head"><div><h3>Identité de la marque</h3><p>Informations visibles sur toutes les interfaces et tous les documents.</p></div></div>
<label>Nom de la plateforme<input name="name" value="<?= htmlspecialchars($brand['name']) ?>" required></label>
<div class="branding-assets">
<label class="branding-logo-upload"><span class="brand-logo-preview"><?php if(!empty($brand['logo'])): ?><img src="<?= htmlspecialchars($brand['logo']) ?>" alt="Logo actuel"><?php else: ?><b>IF</b><?php endif ?></span><span><strong>Logo officiel</strong><small>JPG, PNG ou WebP · 2 Mo maximum</small><input type="file" name="logo" accept="image/jpeg,image/png,image/webp"></span></label>
<label class="branding-logo-upload"><span class="brand-logo-preview favicon-preview"><?php if(!empty($brand['favicon'])): ?><img src="<?= htmlspecialchars($brand['favicon']) ?>" alt="Favicon actuel"><?php elseif(!empty($brand['logo'])): ?><img src="<?= htmlspecialchars($brand['logo']) ?>" alt=""><?php else: ?><b>IF</b><?php endif ?></span><span><strong>Favicon</strong><small>PNG, JPG, WebP ou ICO · 1 Mo maximum</small><input type="file" name="favicon" accept="image/png,image/jpeg,image/webp,image/x-icon,image/vnd.microsoft.icon"></span></label>
<label class="branding-logo-upload"><span class="brand-logo-preview signature-preview"><?php if(!empty($brand['signature'])): ?><img src="<?= htmlspecialchars($brand['signature']) ?>" alt="Signature actuelle"><?php else: ?><b>✍</b><?php endif ?></span><span><strong>Signature officielle IFMAP</strong><small>PNG ou JPG · idéalement fond transparent · 2 Mo maximum</small><input type="file" name="signature" accept="image/jpeg,image/png"></span></label>
</div></section>
<section class="panel form-panel"><div class="panel-head"><div><h3>Palette officielle</h3><p>Appliquée aux interfaces, bannières, cartes, boutons et fichiers imprimables.</p></div></div><div class="color-fields"><label>Couleur principale<div class="color-input"><input type="color" name="primary" value="<?= htmlspecialchars($brand['primary']) ?>"><input data-color-text value="<?= htmlspecialchars($brand['primary']) ?>"></div></label><label>Couleur d’accent<div class="color-input"><input type="color" name="accent" value="<?= htmlspecialchars($brand['accent']) ?>"><input data-color-text value="<?= htmlspecialchars($brand['accent']) ?>"></div></label></div></section>
<section class="panel document-scope"><h3>Éléments pilotés automatiquement par ce branding</h3><div><span>✓ En-tête et pied de page</span><span>✓ Hero et bannières</span><span>✓ Catalogue et cartes de formation</span><span>✓ Actualités et articles</span><span>✓ Logo et favicon</span><span>✓ Diplômes et attestations</span><span>✓ Signature officielle</span><span>✓ Bons de commande et livraison</span><span>✓ Exports PDF</span><span>✓ QR codes de vérification</span></div></section>
<button class="btn primary save-brand">Enregistrer le branding global</button>
</div>
<aside class="panel preview-panel"><div class="panel-head"><div><h3>Aperçu du document</h3><p>Diplôme et attestation</p></div></div><div class="brand-document-preview" style="--preview-primary:<?= htmlspecialchars($brand['primary']) ?>;--preview-accent:<?= htmlspecialchars($brand['accent']) ?>"><div><?php if(!empty($brand['logo'])): ?><img src="<?= htmlspecialchars($brand['logo']) ?>" alt=""><?php else: ?><b>IF</b><?php endif ?><strong><?= htmlspecialchars($brand['name']) ?></strong></div><small>CERTIFICATION OFFICIELLE</small><h2>DIPLÔME DE RÉUSSITE</h2><i></i><p>Décerné à</p><h3>Nom de l’apprenant</h3><span>FORMATION PROFESSIONNELLE</span><?php if(!empty($brand['signature'])): ?><div class="preview-signature"><img src="<?= htmlspecialchars($brand['signature']) ?>" alt="Signature"></div><?php endif ?></div><p class="preview-note">Les modifications s’appliquent automatiquement au site et aux nouveaux documents.</p></aside>
</form>
<style>.branding-assets{display:grid;gap:12px}.branding-logo-upload{display:flex!important;align-items:center;gap:15px;border:1px dashed var(--line);border-radius:12px;padding:15px;cursor:pointer}.branding-logo-upload>span:last-child{display:flex;flex-direction:column;gap:5px}.brand-logo-preview{width:76px;height:64px;border-radius:10px;background:#f1f3f2;display:grid;place-items:center;overflow:hidden}.brand-logo-preview img{max-width:100%;max-height:100%;object-fit:contain}.favicon-preview{width:64px;height:64px}.signature-preview{width:120px}.branding-logo-upload input{margin-top:5px}.document-scope{padding:22px;margin-top:16px}.document-scope>div{display:grid;grid-template-columns:1fr 1fr;gap:10px;color:var(--muted);font-size:10px}.brand-document-preview{margin:15px;padding:24px 15px;border:7px solid var(--preview-primary);outline:1px solid var(--preview-accent);outline-offset:-13px;text-align:center;aspect-ratio:1.414;background:#fff;position:relative}.brand-document-preview>div:first-child{display:flex;align-items:center;justify-content:center;gap:8px}.brand-document-preview img{max-width:55px;max-height:40px}.brand-document-preview>small{display:block;color:var(--preview-accent);font-size:6px;letter-spacing:2px;margin-top:30px}.brand-document-preview h2{font:800 17px Georgia;margin:8px}.brand-document-preview>i{display:block;width:45px;height:2px;background:var(--preview-accent);margin:auto}.brand-document-preview p{font-size:7px;margin-top:25px}.brand-document-preview h3{font:italic 700 14px Georgia;border-bottom:1px solid var(--preview-accent);display:inline-block}.brand-document-preview>span{display:block;font-size:7px}.preview-signature{position:absolute;left:35px;bottom:25px}.preview-signature img{max-width:90px;max-height:38px}.save-brand{margin-top:16px}@media(max-width:650px){.document-scope>div{grid-template-columns:1fr}}</style>
