<?php
$script = str_replace('\\', '/', $_SERVER['SCRIPT_NAME'] ?? '/index.php');
$basePath = rtrim(str_replace('/index.php', '', $script), '/');
$brandingAction = $basePath . '/admin/branding';
?>
<section class="admin-welcome"><div><p class="eyebrow">IDENTITÉ GLOBALE</p><h1>Branding et documents</h1><p>Le logo, le favicon, la signature et la palette sont utilisés par la plateforme et les documents officiels.</p></div><button class="btn secondary" type="button" data-reset-brand>↺ Réinitialiser les couleurs</button></section>
<form class="branding-grid" method="post" action="<?= htmlspecialchars($brandingAction) ?>" enctype="multipart/form-data" data-brand-form>
<div>
<section class="panel form-panel"><div class="panel-head"><div><h3>Identité de la marque</h3><p>Glissez-déposez vos fichiers ou cliquez dans une zone pour les remplacer.</p></div></div>
<label>Nom de la plateforme<input name="name" value="<?= htmlspecialchars($brand['name']) ?>" required></label>
<div class="brand-drop-grid">
<label class="brand-drop" data-drop><span class="brand-drop-preview" data-preview><?php if(!empty($brand['logo'])): ?><img src="<?= htmlspecialchars($brand['logo']) ?>" alt="Logo actuel"><?php else: ?><b>IF</b><?php endif ?></span><strong>Logo officiel</strong><small>PNG, JPG ou WebP · 2 Mo maximum<br>Utilisé dans l’en-tête, le pied de page et les documents.</small><input type="file" name="logo" accept="image/jpeg,image/png,image/webp"></label>
<label class="brand-drop" data-drop><span class="brand-drop-preview favicon" data-preview><?php if(!empty($brand['favicon'])): ?><img src="<?= htmlspecialchars($brand['favicon']) ?>" alt="Favicon actuel"><?php elseif(!empty($brand['logo'])): ?><img src="<?= htmlspecialchars($brand['logo']) ?>" alt="Aperçu favicon"><?php else: ?><b>IF</b><?php endif ?></span><strong>Favicon</strong><small>PNG, JPG, WebP ou ICO · 1 Mo maximum<br>Affiché dans l’onglet du navigateur.</small><input type="file" name="favicon" accept="image/png,image/jpeg,image/webp,image/x-icon,image/vnd.microsoft.icon"></label>
<label class="brand-drop" data-drop><span class="brand-drop-preview signature" data-preview><?php if(!empty($brand['signature'])): ?><img src="<?= htmlspecialchars($brand['signature']) ?>" alt="Signature actuelle"><?php else: ?><b>✍</b><?php endif ?></span><strong>Signature officielle IFMAP</strong><small>PNG transparent recommandé ou JPG · 2 Mo maximum<br>Apposée aux diplômes officiels.</small><input type="file" name="signature" accept="image/jpeg,image/png"></label>
</div></section>
<section class="panel form-panel"><div class="panel-head"><div><h3>Palette officielle</h3><p>Les bannières, accents, filtres et zones institutionnelles utilisent automatiquement cette palette.</p></div></div><div class="color-fields"><label>Couleur principale<div class="color-input"><input type="color" name="primary" value="<?= htmlspecialchars($brand['primary']) ?>"><input data-color-text value="<?= htmlspecialchars($brand['primary']) ?>"></div></label><label>Couleur d’accent<div class="color-input"><input type="color" name="accent" value="<?= htmlspecialchars($brand['accent']) ?>"><input data-color-text value="<?= htmlspecialchars($brand['accent']) ?>"></div></label></div></section>
<section class="panel document-scope"><h3>Application automatique</h3><div><span>✓ En-tête et pied de page</span><span>✓ Favicon navigateur</span><span>✓ Bannières et hero</span><span>✓ Formations et boutique</span><span>✓ Actualités et articles</span><span>✓ Diplômes et attestations</span><span>✓ Signature officielle</span><span>✓ Bons et exports PDF</span></div></section>
<button class="btn success save-brand" type="submit">✓ Enregistrer et appliquer le branding</button>
</div>
<aside class="panel preview-panel"><div class="panel-head"><div><h3>Aperçu instantané</h3><p>Diplôme et identité</p></div></div><div class="brand-document-preview" style="--preview-primary:<?= htmlspecialchars($brand['primary']) ?>;--preview-accent:<?= htmlspecialchars($brand['accent']) ?>"><div><?php if(!empty($brand['logo'])): ?><img src="<?= htmlspecialchars($brand['logo']) ?>" alt=""><?php else: ?><b>IF</b><?php endif ?><strong><?= htmlspecialchars($brand['name']) ?></strong></div><small>CERTIFICATION OFFICIELLE</small><h2>DIPLÔME DE RÉUSSITE</h2><i></i><p>Décerné à</p><h3>Nom de l’apprenant</h3><span>FORMATION PROFESSIONNELLE</span><?php if(!empty($brand['signature'])): ?><div class="preview-signature"><img src="<?= htmlspecialchars($brand['signature']) ?>" alt="Signature"></div><?php endif ?></div><p class="preview-note">Après enregistrement, rechargez une page publique pour voir le branding appliqué.</p></aside>
</form>
<style>.document-scope{padding:22px;margin-top:16px}.document-scope>div{display:grid;grid-template-columns:1fr 1fr;gap:10px;color:var(--muted);font-size:10px}.brand-document-preview{margin:15px;padding:24px 15px;border:7px solid var(--preview-primary);outline:1px solid var(--preview-accent);outline-offset:-13px;text-align:center;aspect-ratio:1.414;background:#fff;position:relative}.brand-document-preview>div:first-child{display:flex;align-items:center;justify-content:center;gap:8px}.brand-document-preview img{max-width:55px;max-height:40px;object-fit:contain}.brand-document-preview>small{display:block;color:var(--preview-accent);font-size:6px;letter-spacing:2px;margin-top:30px}.brand-document-preview h2{font:800 17px Georgia;margin:8px}.brand-document-preview>i{display:block;width:45px;height:2px;background:var(--preview-accent);margin:auto}.brand-document-preview p{font-size:7px;margin-top:25px}.brand-document-preview h3{font:italic 700 14px Georgia;border-bottom:1px solid var(--preview-accent);display:inline-block}.brand-document-preview>span{display:block;font-size:7px}.preview-signature{position:absolute;left:35px;bottom:25px}.preview-signature img{max-width:90px;max-height:38px}.save-brand{margin-top:16px;min-height:48px}@media(max-width:650px){.document-scope>div{grid-template-columns:1fr}}</style>
<script>(()=>{document.querySelectorAll('[data-drop]').forEach(zone=>{const input=zone.querySelector('input[type=file]'),preview=zone.querySelector('[data-preview]');const show=file=>{if(!file)return;const r=new FileReader();r.onload=()=>{preview.innerHTML='<img alt="Aperçu">';preview.querySelector('img').src=r.result};r.readAsDataURL(file)};['dragenter','dragover'].forEach(e=>zone.addEventListener(e,x=>{x.preventDefault();zone.classList.add('is-dragging')}));['dragleave','drop'].forEach(e=>zone.addEventListener(e,x=>{x.preventDefault();zone.classList.remove('is-dragging')}));zone.addEventListener('drop',e=>{const f=e.dataTransfer.files?.[0];if(!f)return;const dt=new DataTransfer();dt.items.add(f);input.files=dt.files;show(f)});input.addEventListener('change',()=>show(input.files?.[0]))});})();</script>
