<?php $editId=(int)($_GET['edit']??0);$editing=null;foreach($pages as $p)if((int)$p['id']===$editId)$editing=$p; ?>
<section class="seo-hero"><div><span class="analytics-kicker">SEO CONTROL CENTER</span><h1>Référencement professionnel IFMAP.</h1><p>Pilotez les balises, l’indexation, le partage social, le sitemap et les données structurées page par page.</p></div><div class="seo-health"><span>Couverture configurée</span><strong><?= count($pages) ?></strong><small>page(s) personnalisée(s)</small></div></section>

<div class="seo-grid">
<section class="seo-editor analytics-panel">
<div class="panel-title"><div><span><?= $editing?'MODIFIER':'NOUVELLE PAGE' ?></span><h2><?= $editing?'Optimiser '.$editing['path']:'Configurer une page' ?></h2></div><?php if($editing): ?><a href="/admin/referencement" class="btn secondary">Nouveau</a><?php endif ?></div>
<form method="post" action="/admin/referencement" class="seo-form">
<input type="hidden" name="action" value="page">
<div class="seo-row"><label class="wide"><span>Chemin de la page</span><input name="path" required value="<?= htmlspecialchars($editing['path']??'') ?>" placeholder="/formations"><small>Ex. /formations, /boutique/sabre-de-jauge</small></label></div>
<div class="seo-row two"><label><span>Meta title</span><input name="title" maxlength="190" value="<?= htmlspecialchars($editing['title']??'') ?>" data-seo-title><small><b data-title-count>0</b>/65 caractères recommandés</small></label><label><span>Canonical URL</span><input type="url" name="canonical_url" value="<?= htmlspecialchars($editing['canonical_url']??'') ?>" placeholder="https://mooc.ifmap.ci/formations"></label></div>
<label><span>Meta description</span><textarea name="description" maxlength="320" rows="3" data-seo-description><?= htmlspecialchars($editing['description']??'') ?></textarea><small><b data-description-count>0</b>/170 caractères recommandés</small></label>
<label><span>Mots-clés éditoriaux</span><input name="keywords" maxlength="500" value="<?= htmlspecialchars($editing['keywords']??'') ?>" placeholder="formation aval pétrolier, pompiste, station-service"></label>
<div class="seo-index-box"><label><input type="checkbox" name="robots_index" <?= !isset($editing['robots_index'])||$editing['robots_index']?'checked':'' ?>> Autoriser l’indexation</label><label><input type="checkbox" name="robots_follow" <?= !isset($editing['robots_follow'])||$editing['robots_follow']?'checked':'' ?>> Suivre les liens</label></div>
<div class="seo-divider"><span>APERÇU SOCIAL</span></div>
<div class="seo-row two"><label><span>Open Graph title</span><input name="og_title" maxlength="190" value="<?= htmlspecialchars($editing['og_title']??'') ?>"></label><label><span>Image de partage</span><input name="og_image" maxlength="500" value="<?= htmlspecialchars($editing['og_image']??'') ?>" placeholder="/public/uploads/... ou URL complète"></label></div>
<label><span>Open Graph description</span><textarea name="og_description" maxlength="320" rows="2"><?= htmlspecialchars($editing['og_description']??'') ?></textarea></label>
<div class="seo-row two"><label><span>Twitter Card</span><select name="twitter_card"><option value="summary_large_image" <?= ($editing['twitter_card']??'summary_large_image')==='summary_large_image'?'selected':'' ?>>Grande image</option><option value="summary" <?= ($editing['twitter_card']??'')==='summary'?'selected':'' ?>>Résumé compact</option></select></label><label><span>Fréquence sitemap</span><select name="sitemap_changefreq"><?php foreach(['daily'=>'Quotidienne','weekly'=>'Hebdomadaire','monthly'=>'Mensuelle','yearly'=>'Annuelle'] as $v=>$l): ?><option value="<?= $v ?>" <?= ($editing['sitemap_changefreq']??'weekly')===$v?'selected':'' ?>><?= $l ?></option><?php endforeach ?></select></label></div>
<label><span>Priorité sitemap</span><input type="number" name="sitemap_priority" min="0.1" max="1" step="0.1" value="<?= htmlspecialchars((string)($editing['sitemap_priority']??'0.5')) ?>"></label>
<div class="seo-divider"><span>DONNÉES STRUCTURÉES</span></div>
<label><span>JSON-LD personnalisé</span><textarea name="schema_json" rows="8" class="code-area" placeholder='{"@context":"https://schema.org","@type":"Course",...}'><?= htmlspecialchars($editing['schema_json']??'') ?></textarea><small>Laissez vide pour utiliser le schema.org automatique IFMAP.</small></label>
<div class="seo-preview" data-seo-preview><small>APERÇU GOOGLE</small><a data-preview-title><?= htmlspecialchars($editing['title']??'Titre de votre page — IFMAP') ?></a><span><?= htmlspecialchars($editing['canonical_url']??'https://mooc.ifmap.ci/...') ?></span><p data-preview-description><?= htmlspecialchars($editing['description']??'La description de votre page apparaîtra ici dans les résultats de recherche.') ?></p></div>
<button class="btn primary">Enregistrer le référencement</button>
</form>
</section>

<aside class="seo-side">
<section class="analytics-panel"><div class="panel-title"><div><span>RÉGLAGES GLOBAUX</span><h2>Identité SEO</h2></div></div><form method="post" action="/admin/referencement" class="seo-form compact"><input type="hidden" name="action" value="settings"><label><span>Nom de l’organisation</span><input name="organization_name" value="<?= htmlspecialchars($settings['organization_name']??'IFMAP Learning') ?>"></label><label><span>Description par défaut</span><textarea name="default_description" rows="4"><?= htmlspecialchars($settings['default_description']??'') ?></textarea></label><label><span>Image sociale par défaut</span><input name="default_og_image" value="<?= htmlspecialchars($settings['default_og_image']??'') ?>"></label><label><span>Google Search Console</span><input name="google_site_verification" value="<?= htmlspecialchars($settings['google_site_verification']??'') ?>" placeholder="Code de vérification"></label><label><span>Bing Webmaster Tools</span><input name="bing_site_verification" value="<?= htmlspecialchars($settings['bing_site_verification']??'') ?>"></label><button class="btn secondary">Enregistrer les réglages</button></form></section>
<section class="analytics-panel seo-links"><div class="panel-title"><div><span>SEO TECHNIQUE</span><h2>Fichiers générés</h2></div></div><a href="/sitemap.xml" target="_blank"><strong>sitemap.xml</strong><small>Pages, formations, produits et actualités publiés</small><span>↗</span></a><a href="/robots.txt" target="_blank"><strong>robots.txt</strong><small>Règles d’exploration des moteurs</small><span>↗</span></a></section>
</aside>
</div>

<section class="analytics-panel seo-pages-panel"><div class="panel-title"><div><span>AUDIT DES PAGES</span><h2>Couverture SEO personnalisée</h2></div><small>Score indicatif basé sur les bonnes pratiques essentielles</small></div><div class="table-scroll"><table class="analytics-table"><thead><tr><th>Page</th><th>Title</th><th>Description</th><th>Index</th><th>Score</th><th></th></tr></thead><tbody><?php foreach($pages as $p): ?><tr><td><strong><?= htmlspecialchars($p['path']) ?></strong><small><?= htmlspecialchars($p['canonical_url']?:'Canonical automatique') ?></small></td><td><?= htmlspecialchars($p['title']?:'Automatique') ?><small><?= mb_strlen((string)$p['title']) ?> caractères</small></td><td><?= htmlspecialchars(mb_strimwidth((string)$p['description'],0,90,'…')) ?><small><?= mb_strlen((string)$p['description']) ?> caractères</small></td><td><span class="seo-status <?= $p['robots_index']?'ok':'off' ?>"><?= $p['robots_index']?'Indexable':'Noindex' ?></span></td><td><div class="seo-score"><i><b style="width:<?= (int)$p['score'] ?>%"></b></i><strong><?= (int)$p['score'] ?>/100</strong></div></td><td class="seo-actions"><a class="btn secondary" href="/admin/referencement?edit=<?= (int)$p['id'] ?>">Modifier</a><form method="post" action="/admin/referencement/supprimer" onsubmit="return confirm('Supprimer cette configuration SEO ?')"><input type="hidden" name="id" value="<?= (int)$p['id'] ?>"><button class="icon-btn">×</button></form></td></tr><?php endforeach ?><?php if(!$pages): ?><tr><td colspan="6"><div class="admin-empty">Aucune page personnalisée. Les balises automatiques continuent de fonctionner sur le site.</div></td></tr><?php endif ?></tbody></table></div></section>
