<?php
use App\Controllers\AdminController;
use App\Controllers\DashboardController;
use App\Controllers\SiteController;
use App\Controllers\AuthController;
use App\Controllers\AcademyController;
use App\Controllers\ProfileController;

$router->get('/', [SiteController::class, 'home']);
$router->get('/favicon.ico', function (): void { header('Location: /public/favicon.svg', true, 302); });
$router->get('/formations', [SiteController::class, 'trainings']);
$router->get('/formations/{slug}', [SiteController::class, 'training']);
$router->get('/boutique', [SiteController::class, 'shop']);
$router->get('/actualites', [SiteController::class, 'news']);
$router->get('/actualites/{slug}', [SiteController::class, 'article']);
$router->post('/actualites/commenter', [SiteController::class, 'commentArticle']);
$router->get('/boutique/{slug}', [SiteController::class, 'product']);
$router->get('/panier', [SiteController::class, 'cart']);
$router->post('/panier/ajouter', [SiteController::class, 'addCart']);
$router->post('/panier/supprimer', [SiteController::class, 'removeCart']);
$router->post('/panier/vider', [SiteController::class, 'clearCart']);
$router->post('/panier/coupon', [SiteController::class, 'applyCoupon']);
$router->get('/commande', [SiteController::class, 'checkout']);
$router->post('/commande', [SiteController::class, 'placeOrder']);
$router->get('/commande/confirmation', [SiteController::class, 'confirmation']);
$router->get('/commande/telecharger', [SiteController::class, 'downloadProduct']);
$router->get('/paiement/cinetpay/retour', [SiteController::class, 'cinetPayReturn']);
$router->post('/paiement/cinetpay/retour', [SiteController::class, 'cinetPayReturn']);
$router->get('/paiement/cinetpay/notification', [SiteController::class, 'cinetPayNotify']);
$router->post('/paiement/cinetpay/notification', [SiteController::class, 'cinetPayNotify']);
$router->get('/mon-compte', function (): void {
    $base = rtrim(str_replace('/index.php', '', str_replace('\\', '/', $_SERVER['SCRIPT_NAME'] ?? '/index.php')), '/');
    header('Location: ' . $base . (!empty($_SESSION['user']) ? '/academie' : '/connexion')); exit;
});
$router->get('/profil', [ProfileController::class, 'show']);
$router->post('/profil', [ProfileController::class, 'save']);
$router->post('/profil/mot-de-passe', [SiteController::class, 'savePassword']);
$router->get('/connexion', [AuthController::class, 'showLogin']);
$router->post('/connexion', [AuthController::class, 'login']);
$router->get('/inscription', [AuthController::class, 'showRegister']);
$router->post('/inscription', [AuthController::class, 'register']);
$router->get('/activation', [AuthController::class, 'showActivation']);
$router->post('/activation', [AuthController::class, 'activate']);
$router->post('/activation/renvoyer', [AuthController::class, 'resendOtp']);
$router->post('/deconnexion', [AuthController::class, 'logout']);
$router->get('/academie', [DashboardController::class, 'index']);
$router->post('/academie/inscrire', [DashboardController::class, 'enroll']);
$router->get('/dashboard', function (): void {
    $base = rtrim(str_replace('/index.php', '', str_replace('\\', '/', $_SERVER['SCRIPT_NAME'] ?? '/index.php')), '/');
    $target = !empty($_SESSION['admin_authenticated']) ? '/admin' : (!empty($_SESSION['user']) ? '/academie' : '/connexion');
    header('Location: ' . $base . $target); exit;
});
$router->get('/catalogue', [DashboardController::class, 'catalog']);
$router->get('/cours', [DashboardController::class, 'course']);
$router->get('/academie/formation', [AcademyController::class, 'course']);
$router->get('/academie/lecon', [AcademyController::class, 'lesson']);
$router->post('/academie/lecon/terminer', [AcademyController::class, 'completeLesson']);
$router->get('/academie/composition', [AcademyController::class, 'assessment']);
$router->post('/academie/composition', [AcademyController::class, 'submitAssessment']);
$router->get('/academie/diplome', [AcademyController::class, 'certificate']);
$router->get('/academie/certificat/specimen', [AcademyController::class, 'specimen']);
$router->get('/academie/attestation', [AcademyController::class, 'attestation']);
$router->get('/academie/livret', [AcademyController::class, 'transcript']);
$router->get('/academie/certificats', [AcademyController::class, 'certificates']);
$router->get('/certificats/verifier', [AcademyController::class, 'verifyCertificate']);
$router->get('/admin', [AdminController::class, 'index']);
$router->get('/admin/connexion', [AdminController::class, 'login']);
$router->post('/admin/connexion', [AdminController::class, 'authenticate']);
$router->post('/admin/deconnexion', [AdminController::class, 'logout']);
$router->get('/admin/cours', [AdminController::class, 'courses']);
$router->get('/admin/cours/nouveau', [AdminController::class, 'courseForm']);
$router->post('/admin/cours/nouveau', [AdminController::class, 'saveCourse']);
$router->get('/admin/cours/modifier', [AdminController::class, 'editCourse']);
$router->post('/admin/cours/modifier', [AdminController::class, 'updateCourse']);
$router->get('/admin/cours/programme', [AdminController::class, 'builder']);
$router->get('/admin/cours/apercu', [AdminController::class, 'previewCourse']);
$router->get('/admin/cours/apercu-lecon', [AdminController::class, 'previewLesson']);
$router->post('/admin/cours/programme', [AdminController::class, 'builderAction']);
$router->post('/admin/r2/video-url', [AdminController::class, 'r2VideoUploadUrl']);
$router->get('/admin/cours/brouillons-lecons', [AdminController::class, 'lessonDrafts']);
$router->get('/admin/cours/examens', [AdminController::class, 'exams']);
$router->post('/admin/cours/supprimer', [AdminController::class, 'deleteCourse']);
$router->get('/admin/produits', [AdminController::class, 'products']);
$router->get('/admin/produits/nouveau', [AdminController::class, 'productForm']);
$router->post('/admin/produits/enregistrer', [AdminController::class, 'saveProduct']);
$router->get('/admin/produits/modifier', [AdminController::class, 'productForm']);
$router->post('/admin/produits/supprimer', [AdminController::class, 'deleteProduct']);
$router->post('/admin/produits/stock', [AdminController::class, 'adjustStock']);
$router->get('/admin/coupons', [AdminController::class, 'coupons']);
$router->post('/admin/coupons', [AdminController::class, 'saveCoupon']);
$router->post('/admin/coupons/supprimer', [AdminController::class, 'deleteCoupon']);
$router->get('/admin/utilisateurs', [AdminController::class, 'users']);
$router->post('/admin/utilisateurs/activer', [AdminController::class, 'activateUser']);
$router->get('/admin/utilisateurs/modifier', [AdminController::class, 'editUser']);
$router->post('/admin/utilisateurs/modifier', [AdminController::class, 'updateUser']);
$router->get('/admin/inscriptions', [AdminController::class, 'enrollments']);
$router->get('/admin/commandes', [AdminController::class, 'orders']);
$router->post('/admin/commandes/statut', [AdminController::class, 'updateOrderStatus']);
$router->get('/admin/documents', [AdminController::class, 'documents']);
$router->get('/admin/actualites', [AdminController::class, 'news']);
$router->post('/admin/actualites', [AdminController::class, 'savePost']);
$router->get('/admin/documents/export-commandes', [AdminController::class, 'exportOrders']);
$router->get('/admin/documents/export-inscriptions', [AdminController::class, 'exportEnrollments']);
$router->get('/admin/documents/commande', [AdminController::class, 'orderDocument']);
$router->get('/admin/documents/livraison', [AdminController::class, 'deliveryDocument']);
$router->get('/admin/branding', [AdminController::class, 'branding']);
$router->post('/admin/branding', [AdminController::class, 'saveBranding']);
