<?php
use App\Controllers\AdminController;
use App\Controllers\DashboardController;
use App\Controllers\SiteController;
use App\Controllers\AuthController;
use App\Controllers\AcademyController;

$router->get('/', [SiteController::class, 'home']);
$router->get('/formations', [SiteController::class, 'trainings']);
$router->get('/formations/sous-gerant-station-service', [SiteController::class, 'training']);
$router->get('/boutique', [SiteController::class, 'shop']);
$router->get('/boutique/sabre-de-jauge', [SiteController::class, 'product']);
$router->get('/panier', [SiteController::class, 'cart']);
$router->post('/panier/ajouter', [SiteController::class, 'addCart']);
$router->post('/panier/supprimer', [SiteController::class, 'removeCart']);
$router->post('/panier/vider', [SiteController::class, 'clearCart']);
$router->get('/commande', [SiteController::class, 'checkout']);
$router->post('/commande', [SiteController::class, 'placeOrder']);
$router->get('/commande/confirmation', [SiteController::class, 'confirmation']);
$router->get('/mon-compte', [SiteController::class, 'account']);
$router->get('/profil', [SiteController::class, 'profile']);
$router->post('/profil', [SiteController::class, 'saveProfile']);
$router->post('/profil/mot-de-passe', [SiteController::class, 'savePassword']);
$router->get('/connexion', [AuthController::class, 'showLogin']);
$router->post('/connexion', [AuthController::class, 'login']);
$router->get('/inscription', [AuthController::class, 'showRegister']);
$router->post('/inscription', [AuthController::class, 'register']);
$router->post('/deconnexion', [AuthController::class, 'logout']);
$router->get('/academie', [DashboardController::class, 'index']);
$router->get('/dashboard', function (): void {
    $base = rtrim(str_replace('/index.php', '', str_replace('\\', '/', $_SERVER['SCRIPT_NAME'] ?? '/index.php')), '/');
    $target = !empty($_SESSION['admin_authenticated']) ? '/admin' : (!empty($_SESSION['user']) ? '/academie' : '/connexion');
    header('Location: ' . $base . $target); exit;
});
$router->get('/catalogue', [DashboardController::class, 'catalog']);
$router->get('/cours', [DashboardController::class, 'course']);
$router->get('/academie/formation', [AcademyController::class, 'course']);
$router->get('/academie/lecon', [AcademyController::class, 'lesson']);
$router->post('/academie/lecon/terminer', [AcademyController::class, 'completeLesson']);
$router->get('/academie/composition', [AcademyController::class, 'assessment']);
$router->post('/academie/composition', [AcademyController::class, 'submitAssessment']);
$router->get('/academie/diplome', [AcademyController::class, 'certificate']);
$router->get('/admin', [AdminController::class, 'index']);
$router->get('/admin/connexion', [AdminController::class, 'login']);
$router->post('/admin/connexion', [AdminController::class, 'authenticate']);
$router->post('/admin/deconnexion', [AdminController::class, 'logout']);
$router->get('/admin/cours', [AdminController::class, 'courses']);
$router->get('/admin/cours/nouveau', [AdminController::class, 'courseForm']);
$router->post('/admin/cours/nouveau', [AdminController::class, 'saveCourse']);
$router->get('/admin/cours/modifier', [AdminController::class, 'editCourse']);
$router->post('/admin/cours/modifier', [AdminController::class, 'updateCourse']);
$router->get('/admin/cours/programme', [AdminController::class, 'builder']);
$router->post('/admin/cours/programme', [AdminController::class, 'builderAction']);
$router->post('/admin/cours/supprimer', [AdminController::class, 'deleteCourse']);
$router->get('/admin/produits', [AdminController::class, 'products']);
$router->get('/admin/utilisateurs', [AdminController::class, 'users']);
$router->get('/admin/commandes', [AdminController::class, 'orders']);
$router->get('/admin/branding', [AdminController::class, 'branding']);
$router->post('/admin/branding', [AdminController::class, 'saveBranding']);
