<?php
$isSpecimen=!empty($specimen);
$code=$certificate['verification_code']?:$certificate['reference'];
$scheme=(!empty($_SERVER['HTTPS'])&&$_SERVER['HTTPS']!=='off')?'https':'http';
$base=rtrim(str_replace('/index.php','',str_replace('\\','/',$_SERVER['SCRIPT_NAME']??'/index.php')),'/');
$verifyUrl=$scheme.'://'.($_SERVER['HTTP_HOST']??'localhost').$base.'/certificats/verifier?code='.urlencode($code);
$officialPayload=base64_encode(json_encode(['type'=>'certificate','data'=>$certificate,'specimen'=>$isSpecimen],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES));
?>
<style>.specimen-watermark{position:absolute;z-index:5;left:50%;top:48%;transform:translate(-50%,-50%) rotate(-27deg);color:rgba(204,20,35,.38);border:8px solid rgba(204,20,35,.32);padding:12px 42px;font-size:92px;font-weight:900;letter-spacing:8px;line-height:.8;text-align:center;white-space:nowrap;pointer-events:none}.specimen-watermark small{display:block;font-size:25px;letter-spacing:12px;margin-top:17px}.is-specimen .document-recipient,.is-specimen .document-meta{opacity:.72}.specimen-notice{max-width:280px;padding:14px;border:2px solid rgba(204,20,35,.5);color:#b31222}.specimen-notice code{font-weight:900;letter-spacing:2px}</style>
<div class="document-tools"><button onclick="window.print()">↓ <?= $isSpecimen?'Imprimer le spécimen':'Télécharger / imprimer en PDF' ?></button><a href="/academie/certificats">← Mes certificats</a></div>
<main class="official-document <?= $isSpecimen?'is-specimen':'' ?>" data-official-pdf="<?= htmlspecialchars($officialPayload,ENT_QUOTES,'UTF-8') ?>">
<?php if($isSpecimen): ?><div class="specimen-watermark">SPÉCIMEN<small>NON VALIDE</small></div><?php endif ?>
<div class="document-frame"></div><header><div class="document-brand"><?php if(!empty($brand['logo'])): ?><img src="<?= htmlspecialchars($brand['logo']) ?>" alt="Logo <?= htmlspecialchars($brand['name']) ?>"><?php else: ?><span>IF</span><?php endif ?><div><strong><?= htmlspecialchars($brand['name']) ?></strong><small>INSTITUT DE FORMATION AUX MÉTIERS</small></div></div><div class="document-reference">RÉF. <?= htmlspecialchars($isSpecimen?'APERÇU NON ÉMIS':$certificate['reference']) ?></div></header>
<section class="document-title"><p><?= $isSpecimen?'APERÇU AVANT VALIDATION':'CERTIFICATION OFFICIELLE' ?></p><h1>DIPLÔME DE RÉUSSITE</h1><i></i></section><section class="document-recipient"><p>Le présent diplôme certifie que</p><h2><?= htmlspecialchars($certificate['user_name']) ?></h2><p>a suivi et validé avec succès la formation</p><h3><?= htmlspecialchars($certificate['course_title']) ?></h3></section>
<section class="document-meta"><div><small>DURÉE DU PARCOURS</small><strong><?= htmlspecialchars($certificate['duration_label']??'Formation complète') ?></strong></div><div><small>SCORE FINAL</small><strong><?= $isSpecimen?'À OBTENIR':(int)$certificate['final_score'].'%' ?></strong></div><div><small>DATE DE DÉLIVRANCE</small><strong><?= $isSpecimen?'APRÈS VALIDATION':date('d/m/Y',strtotime($certificate['issued_at'])) ?></strong></div></section>
<footer><div class="signature"><i></i><strong>Direction <?= htmlspecialchars($brand['name']) ?></strong><small><?= $isSpecimen?'Signature non apposée':'Signature autorisée' ?></small></div><?php if($isSpecimen): ?><div class="document-verification specimen-notice"><div><strong>APERÇU NON VÉRIFIABLE</strong><small>Ce document n’est ni un diplôme ni une preuve de réussite.</small><code>NON-VALIDE</code></div></div><?php else: ?><div class="document-verification"><img src="https://api.qrserver.com/v1/create-qr-code/?size=120x120&amp;data=<?= urlencode($verifyUrl) ?>" alt="QR code de vérification"><div><strong>DOCUMENT VÉRIFIABLE</strong><small>Scannez le QR code ou utilisez :</small><code><?= htmlspecialchars($code) ?></code></div></div><?php endif ?></footer>
<div class="document-bottom"><?= $isSpecimen?'SPÉCIMEN SANS VALEUR OFFICIELLE · généré pour prévisualisation':('Document généré automatiquement par la plateforme '.htmlspecialchars($brand['name']).' · '.htmlspecialchars($verifyUrl)) ?></div></main>
