<?php
namespace App\Controllers;

use App\Core\Database;
use App\Core\View;
use App\Repositories\MentorshipRepository;
use App\Services\LiveSessionService;
use App\Services\PaiementPro;
use App\Services\SecureSettings;
use App\Services\SmtpMailer;

final class MentorshipController
{
    private function base(string $path=''): string { $base=rtrim(str_replace('/index.php','',str_replace('\\','/',$_SERVER['SCRIPT_NAME']??'/index.php')),'/');return $base.$path; }
    private function redirect(string $path): never { header('Location: '.$this->base($path));exit; }
    private function user(): array { if(empty($_SESSION['user'])){$requested=parse_url($_SERVER['REQUEST_URI']??'/mentorat',PHP_URL_PATH)?:'/mentorat';$_SESSION['intended_url']=$requested;$this->redirect('/connexion');}return $_SESSION['user']; }
    private function admin(): void { if(empty($_SESSION['admin_authenticated']))$this->redirect('/admin/connexion'); }

    public function catalogue(): void { $repo=new MentorshipRepository();View::render('site/mentors',['title'=>'Mentorat professionnel','active'=>'mentorship','mentors'=>$repo->mentors()],'site'); }
    public function dashboard(): void { $u=$this->user();$repo=new MentorshipRepository();View::render('mentorship/dashboard',['title'=>'Mon mentorat','active'=>'mentorship','mentors'=>$repo->mentors(),'requests'=>$repo->learnerRequests((int)$u['id']),'flash'=>$_SESSION['mentor_flash']??null,'error'=>$_SESSION['mentor_error']??null]);unset($_SESSION['mentor_flash'],$_SESSION['mentor_error']); }
    public function mentorDashboard(): void { $u=$this->user();$repo=new MentorshipRepository();$profile=$repo->mentor((int)$u['id']);if(($u['role']??'')!=='mentor'&&($profile['dossier_status']??'')!=='approved')$this->redirect('/devenir-mentor');View::render('mentorship/mentor-dashboard',['title'=>'Espace mentor','active'=>'mentor','profile'=>$profile,'requests'=>$repo->mentorRequests((int)$u['id']),'flash'=>$_SESSION['mentor_flash']??null]);unset($_SESSION['mentor_flash']); }

    public function apply(): void { $u=$this->user();$repo=new MentorshipRepository();View::render('mentorship/apply',['title'=>'Devenir mentor IFMAP','active'=>'mentorship','profile'=>$repo->mentor((int)$u['id']),'flash'=>$_SESSION['mentor_flash']??null,'error'=>$_SESSION['mentor_error']??null]);unset($_SESSION['mentor_flash'],$_SESSION['mentor_error']); }
    public function submitApplication(): void
    {
        $u=$this->user();$db=Database::connection();$headline=mb_substr(trim((string)($_POST['headline']??'')),0,190);$bio=trim((string)($_POST['bio']??''));$rate=max(0,(int)($_POST['hourly_rate']??0));$years=max(0,min(60,(int)($_POST['years_experience']??0)));if($headline===''||mb_strlen($bio)<80||$rate<1000){$_SESSION['mentor_error']='Complétez le titre, une présentation d’au moins 80 caractères et un tarif valide.';$this->redirect('/devenir-mentor');}
        $db->prepare("INSERT INTO mentor_profiles(user_id,headline,bio,years_experience,hourly_rate,dossier_status) VALUES(?,?,?,?,?,'submitted') ON DUPLICATE KEY UPDATE headline=VALUES(headline),bio=VALUES(bio),years_experience=VALUES(years_experience),hourly_rate=VALUES(hourly_rate),dossier_status=IF(dossier_status='approved','approved','submitted')")->execute([(int)$u['id'],$headline,$bio,$years,$rate]);
        $db->prepare('DELETE FROM mentor_skills WHERE mentor_id=?')->execute([(int)$u['id']]);$skillSt=$db->prepare("INSERT INTO mentor_skills(mentor_id,skill_name,level,verified) VALUES(?,?,?,0)");foreach(array_slice(array_filter(array_map('trim',explode(',',(string)($_POST['skills']??'')))),0,15) as $skill)$skillSt->execute([(int)$u['id'],mb_substr($skill,0,120),'advanced']);
        $this->storeDocuments((int)$u['id']);$_SESSION['mentor_flash']='Votre candidature a été transmise. IFMAP contrôlera le dossier et pourra programmer un entretien avant validation.';$this->redirect('/devenir-mentor');
    }
    private function storeDocuments(int $mentorId): void
    {
        if(empty($_FILES['documents']['tmp_name'])||!is_array($_FILES['documents']['tmp_name']))return;$dir=dirname(__DIR__,2).'/storage/mentor-documents/'.$mentorId;if(!is_dir($dir))mkdir($dir,0775,true);$db=Database::connection();$st=$db->prepare('INSERT INTO mentor_documents(mentor_id,document_type,file_path) VALUES(?,?,?)');foreach($_FILES['documents']['tmp_name'] as $i=>$tmp){if(!$tmp||!is_uploaded_file($tmp)||($_FILES['documents']['size'][$i]??0)>10*1024*1024)continue;$mime=(new \finfo(FILEINFO_MIME_TYPE))->file($tmp);$ext=['application/pdf'=>'pdf','image/jpeg'=>'jpg','image/png'=>'png'][$mime]??null;if(!$ext)continue;$name=bin2hex(random_bytes(10)).'.'.$ext;$dest=$dir.'/'.$name;if(move_uploaded_file($tmp,$dest))$st->execute([$mentorId,'credential','storage/mentor-documents/'.$mentorId.'/'.$name]);}
    }

    public function request(): void
    {
        $u=$this->user();$mentorId=(int)($_POST['mentor_id']??0);$repo=new MentorshipRepository();$mentor=$repo->mentor($mentorId);if(!$mentor||$mentor['dossier_status']!=='approved'){$_SESSION['mentor_error']='Ce mentor n’est pas disponible.';$this->redirect('/academie/mentorat');}$duration=in_array((int)($_POST['duration_minutes']??60),[30,60,90,120],true)?(int)$_POST['duration_minutes']:60;$subject=mb_substr(trim((string)($_POST['subject']??'')),0,190);$goals=trim((string)($_POST['goals']??''));$scheduled=trim((string)($_POST['scheduled_at']??''));if($subject===''||$scheduled===''){$_SESSION['mentor_error']='Précisez votre besoin et une date souhaitée.';$this->redirect('/academie/mentorat');}$amount=round(((float)$mentor['hourly_rate'])*$duration/60);$st=Database::connection()->prepare("INSERT INTO mentorship_requests(learner_id,mentor_id,subject,goals,duration_minutes,scheduled_at,amount,status,payment_status) VALUES(?,?,?,?,?,?,?,'awaiting_payment','unpaid')");$st->execute([(int)$u['id'],$mentorId,$subject,$goals,$duration,date('Y-m-d H:i:s',strtotime($scheduled)),$amount]);$id=(int)Database::connection()->lastInsertId();$_SESSION['mentor_flash']='Demande créée. Le paiement doit obligatoirement être effectué sur IFMAP pour être reconnu.';$this->redirect('/academie/mentorat/payer?id='.$id);
    }
    public function pay(): void
    {
        $u=$this->user();$id=(int)($_GET['id']??$_POST['id']??0);$repo=new MentorshipRepository();$r=$repo->request($id);if(!$r||(int)$r['learner_id']!==(int)$u['id']){http_response_code(404);return;}if($r['payment_status']==='paid')$this->redirect('/academie/mentorat');$db=Database::connection();$reference='MENT-'.date('Ymd').'-'.strtoupper(bin2hex(random_bytes(5)));$token=bin2hex(random_bytes(32));$hash=hash('sha256',$token);$db->prepare("INSERT INTO mentorship_payments(request_id,provider,reference,token_hash,amount,status) VALUES(?,'paiementpro',?,?,?,'initiated') ON DUPLICATE KEY UPDATE reference=VALUES(reference),token_hash=VALUES(token_hash),amount=VALUES(amount),status='initiated'")->execute([$id,$reference,$hash,$r['amount']]);$order=['reference'=>$reference,'total'=>$r['amount'],'user_id'=>$u['id'],'customer_data'=>json_encode(['name'=>$u['name']??$r['learner_name'],'email'=>$u['email']??$r['learner_email'],'phone'=>$u['phone']??$r['learner_phone']])];try{$resp=(new PaiementPro())->initialize($order,$this->publicUrl('/mentorat/paiement/retour?request='.$id),$this->publicUrl('/mentorat/paiement/notification?request='.$id.'&token='.$token));$db->prepare("UPDATE mentorship_payments SET provider_reference=?,status='pending' WHERE request_id=?")->execute([$resp['session_id'],$id]);$db->prepare("UPDATE mentorship_requests SET payment_status='pending' WHERE id=?")->execute([$id]);header('Location: '.$resp['payment_url']);exit;}catch(\Throwable $e){$_SESSION['mentor_error']='Impossible d’ouvrir le paiement en ligne. Réessayez.';$this->redirect('/academie/mentorat');}
    }
    public function paymentNotify(): void
    {
        $id=(int)($_GET['request']??0);$token=(string)($_GET['token']??'');$db=Database::connection();$repo=new MentorshipRepository();$r=$repo->request($id);$st=$db->prepare('SELECT * FROM mentorship_payments WHERE request_id=?');$st->execute([$id]);$p=$st->fetch();$payload=$_POST ?: (json_decode((string)file_get_contents('php://input'),true)?:$_GET);if(!$r||!$p){http_response_code(404);return;}$order=['reference'=>$p['reference'],'total'=>$p['amount'],'user_id'=>$r['learner_id']];$valid=(new PaiementPro())->validNotification($payload,$order,$token,$p['token_hash']);if(!$valid){http_response_code(403);return;}if((string)$payload['responsecode']==='0'){$db->beginTransaction();try{$db->prepare("UPDATE mentorship_payments SET status='paid',payload=? WHERE request_id=?")->execute([json_encode($payload),$id]);$db->prepare("UPDATE mentorship_requests SET payment_status='paid',status='paid' WHERE id=?")->execute([$id]);$this->ensureRoom($id);$db->commit();$this->notifyPaid($r);}catch(\Throwable $e){if($db->inTransaction())$db->rollBack();http_response_code(500);return;}}else{$db->prepare("UPDATE mentorship_payments SET status='failed',payload=? WHERE request_id=?")->execute([json_encode($payload),$id]);$db->prepare("UPDATE mentorship_requests SET payment_status='failed' WHERE id=?")->execute([$id]);}echo 'OK';
    }
    public function paymentReturn(): void { $_SESSION['mentor_flash']='Paiement reçu par la passerelle. La confirmation définitive apparaît dès validation serveur.';$this->redirect('/academie/mentorat'); }
    private function ensureRoom(int $requestId): void { $db=Database::connection();$r=(new MentorshipRepository())->request($requestId);if(!$r)return;$exists=$db->prepare('SELECT id FROM coaching_sessions WHERE request_id=?');$exists->execute([$requestId]);if($exists->fetchColumn())return;$room=(new LiveSessionService())->createRoom($requestId,$r['subject'],$r['scheduled_at']);$db->prepare("INSERT INTO coaching_sessions(request_id,provider,room_name,room_url,room_data,status,starts_at) VALUES(?,?,?,?,?,'ready',?)")->execute([$requestId,$room['provider'],$room['room_name'],$room['room_url'],$room['room_data'],$r['scheduled_at']]); }
    private function notifyPaid(array $r): void { try{$m=new SmtpMailer();if(!$m->configured())return;$m->send($r['learner_email'],'Mentorat IFMAP — paiement confirmé','<h2>Votre séance de mentorat est confirmée</h2><p>Votre paiement a été validé sur la plateforme IFMAP. Aucun paiement effectué en dehors de la plateforme n’est reconnu par IFMAP.</p>');$m->send($r['mentor_email'],'Nouvelle séance de mentorat IFMAP','<h2>Une séance payée vous a été attribuée</h2><p>Consultez votre espace mentor pour la date et la salle de coaching.</p>');}catch(\Throwable){} }
    private function publicUrl(string $path): string { $base=rtrim((string)\App\Core\Env::get('APP_URL',''),'/');if($base===''){$scheme=(!empty($_SERVER['HTTPS'])&&$_SERVER['HTTPS']!=='off')?'https':'http';$base=$scheme.'://'.($_SERVER['HTTP_HOST']??'localhost').$this->base();}return $base.$path; }

    public function room(): void
    {
        $u=$this->user();$id=(int)($_GET['id']??0);$db=Database::connection();$st=$db->prepare("SELECT cs.*,r.learner_id,r.mentor_id,r.subject,r.scheduled_at,l.name learner_name,m.name mentor_name FROM coaching_sessions cs JOIN mentorship_requests r ON r.id=cs.request_id JOIN users l ON l.id=r.learner_id JOIN users m ON m.id=r.mentor_id WHERE cs.id=? LIMIT 1");$st->execute([$id]);$s=$st->fetch();if(!$s||!in_array((int)$u['id'],[(int)$s['learner_id'],(int)$s['mentor_id']],true)){http_response_code(403);return;}View::render('mentorship/live',['title'=>'Coaching en direct','active'=>'mentorship','session'=>$s]);
    }
    public function review(): void { $u=$this->user();$requestId=(int)($_POST['request_id']??0);$rating=max(1,min(5,(int)($_POST['rating']??0)));$repo=new MentorshipRepository();$r=$repo->request($requestId);if(!$r||(int)$r['learner_id']!==(int)$u['id']||$r['status']!=='completed'){$_SESSION['mentor_error']='Cette séance ne peut pas encore être évaluée.';$this->redirect('/academie/mentorat');}$db=Database::connection();$db->prepare("INSERT INTO mentor_reviews(request_id,learner_id,mentor_id,rating,comment,status) VALUES(?,?,?,?,?,'approved') ON DUPLICATE KEY UPDATE rating=VALUES(rating),comment=VALUES(comment)")->execute([$requestId,(int)$u['id'],(int)$r['mentor_id'],$rating,mb_substr(trim((string)($_POST['comment']??'')),0,2000)]);$db->prepare("UPDATE mentor_profiles mp SET rating_avg=(SELECT COALESCE(AVG(rating),0) FROM mentor_reviews WHERE mentor_id=mp.user_id AND status='approved'),rating_count=(SELECT COUNT(*) FROM mentor_reviews WHERE mentor_id=mp.user_id AND status='approved') WHERE user_id=?")->execute([(int)$r['mentor_id']]);$_SESSION['mentor_flash']='Merci pour votre évaluation.';$this->redirect('/academie/mentorat'); }

    public function adminIndex(): void { $this->admin();$repo=new MentorshipRepository();View::render('admin/mentorship',['title'=>'Mentorat & coaching','active'=>'admin-mentorship','mentors'=>$repo->adminMentors(),'requests'=>$repo->adminRequests()],'admin'); }
    public function adminMentorAction(): void
    {
        $this->admin();$id=(int)($_POST['mentor_id']??0);$action=(string)($_POST['action']??'');$db=Database::connection();if($action==='review')$db->prepare("UPDATE mentor_profiles SET dossier_status='review',admin_notes=? WHERE user_id=?")->execute([trim((string)($_POST['admin_notes']??'')),$id]);elseif($action==='interview')$db->prepare("UPDATE mentor_profiles SET dossier_status='interview',interview_at=? WHERE user_id=?")->execute([$_POST['interview_at']?:null,$id]);elseif($action==='approve'){$db->beginTransaction();$db->prepare("UPDATE mentor_profiles SET dossier_status='approved',identity_verified=1,credentials_verified=1,interview_completed=1,verified_at=NOW(),admin_notes=? WHERE user_id=?")->execute([trim((string)($_POST['admin_notes']??'')),$id]);$db->prepare("UPDATE users SET role='mentor' WHERE id=?")->execute([$id]);$db->commit();}elseif($action==='reject')$db->prepare("UPDATE mentor_profiles SET dossier_status='rejected',admin_notes=? WHERE user_id=?")->execute([trim((string)($_POST['admin_notes']??'')),$id]);elseif($action==='verify-skills')$db->prepare("UPDATE mentor_skills SET verified=1,verified_at=NOW() WHERE mentor_id=?")->execute([$id]);$_SESSION['flash']='Dossier mentor mis à jour.';$this->redirect('/admin/mentorat');
    }
    public function adminSessionAction(): void { $this->admin();$id=(int)($_POST['request_id']??0);$action=(string)($_POST['action']??'');$db=Database::connection();if($action==='confirm'){$this->ensureRoom($id);$db->prepare("UPDATE mentorship_requests SET status='confirmed' WHERE id=? AND payment_status='paid'")->execute([$id]);}elseif($action==='complete'){$db->prepare("UPDATE mentorship_requests SET status='completed' WHERE id=?")->execute([$id]);$db->prepare("UPDATE coaching_sessions SET status='completed',ended_at=NOW() WHERE request_id=?")->execute([$id]);}elseif($action==='cancel'){$db->prepare("UPDATE mentorship_requests SET status='cancelled' WHERE id=?")->execute([$id]);$db->prepare("UPDATE coaching_sessions SET status='cancelled' WHERE request_id=?")->execute([$id]);}$_SESSION['flash']='Séance mise à jour.';$this->redirect('/admin/mentorat'); }

    public function integrations(): void { $this->admin();$s=new SecureSettings();View::render('admin/integrations',['title'=>'Intégrations live & mailing','active'=>'admin-integrations','live'=>$s->group('integrations'),'mail'=>$s->group('mail')],'admin'); }
    public function saveIntegrations(): void { $this->admin();$s=new SecureSettings();foreach(['live_provider','jitsi_base_url','daily_domain'] as $k)$s->set($k,trim((string)($_POST[$k]??'')),'integrations');if(trim((string)($_POST['daily_api_key']??''))!=='')$s->set('daily_api_key',trim((string)$_POST['daily_api_key']),'integrations');foreach(['smtp_host','smtp_port','smtp_encryption','smtp_username','smtp_from_address','smtp_from_name'] as $k)$s->set($k,trim((string)($_POST[$k]??'')),'mail');if(trim((string)($_POST['smtp_password']??''))!=='')$s->set('smtp_password',(string)$_POST['smtp_password'],'mail');$_SESSION['flash']='Paramètres d’intégration enregistrés.';$this->redirect('/admin/integrations'); }
    public function testMail(): void { $this->admin();$to=trim((string)($_POST['test_email']??''));try{if(!filter_var($to,FILTER_VALIDATE_EMAIL))throw new \RuntimeException('Adresse invalide.');(new SmtpMailer())->send($to,'Test SMTP IFMAP','<h2>Connexion SMTP opérationnelle</h2><p>Le module de mailing IFMAP peut envoyer des notifications.</p>');$_SESSION['flash']='Email de test envoyé.';}catch(\Throwable $e){$_SESSION['flash']='Test SMTP échoué : '.$e->getMessage();}$this->redirect('/admin/integrations'); }
}
