<?php
$categories=array_values(array_filter(array_unique(array_column($products,'category'))));
?>
<section class="inner-hero shop-hero modern-shop-hero">
    <div class="shop-hero-orb orb-one"></div><div class="shop-hero-orb orb-two"></div>
    <p class="site-kicker">BOUTIQUE PROFESSIONNELLE</p>
    <h1>L’équipement qui accompagne<br><em>votre savoir-faire.</em></h1>
    <p>Recherchez un produit, filtrez par catégorie ou budget et trouvez rapidement l’équipement adapté à votre activité.</p>
    <label class="shop-hero-search" aria-label="Rechercher un produit"><span>⌕</span><input type="search" data-product-search-main placeholder="Quel équipement recherchez-vous ?" autocomplete="off"><kbd>⌘ K</kbd></label>
    <div class="shop-benefits"><span>✓ Matériel sélectionné</span><span>↗ Livraison suivie</span><span>⌁ Conseil IFMAP</span></div>
</section>
<section class="shop-section modern-shop" data-shop-catalog>
    <header class="shop-toolbar">
        <div><p class="site-kicker">NOTRE SÉLECTION</p><h2>Équipements professionnels</h2><small><b data-product-count><?= count($products) ?></b> produit(s) correspondent à votre recherche</small></div>
        <div class="shop-controls"><div class="filter-chips"><button class="active" type="button" data-category="all">Tous les produits</button><?php foreach($categories as $category): ?><button type="button" data-category="<?= htmlspecialchars(mb_strtolower($category)) ?>"><?= htmlspecialchars($category) ?></button><?php endforeach ?></div></div>
    </header>
    <div class="product-filter-panel">
        <label>RECHERCHE RAPIDE<input type="search" data-product-search-secondary placeholder="Nom, catégorie, description…"></label>
        <label>BUDGET MAXIMUM<input type="number" min="0" step="5000" data-product-max-price placeholder="Sans limite"></label>
        <label>TRIER PAR<select data-product-sort><option value="relevance">Pertinence</option><option value="price-asc">Prix croissant</option><option value="price-desc">Prix décroissant</option><option value="name">Nom A–Z</option></select></label>
    </div>
    <div class="product-grid modern-product-grid" data-product-grid><?php foreach($products as $product): $promo=!empty($product['promotional_price']);$displayPrice=$promo?(int)$product['promotional_price']:(int)($product['price']??0); ?>
        <article class="product-card modern-product-card" data-product-category="<?= htmlspecialchars(mb_strtolower($product['category'])) ?>" data-product-searchable="<?= htmlspecialchars(mb_strtolower($product['title'].' '.$product['category'].' '.$product['description'])) ?>" data-product-price="<?= $displayPrice ?>" data-product-name="<?= htmlspecialchars(mb_strtolower($product['title'])) ?>">
            <a class="product-image <?= htmlspecialchars($product['tone']) ?>" href="/boutique/<?= rawurlencode($product['slug']) ?>">
                <?php if($product['image']): ?><img src="<?= htmlspecialchars($product['image']) ?>" alt="<?= htmlspecialchars($product['title']) ?>"><?php else: ?><span class="product-placeholder-mark">IF</span><small>ÉQUIPEMENT PROFESSIONNEL</small><?php endif ?>
                <span class="product-category-pill"><?= htmlspecialchars($product['category']) ?></span><?php if($promo): ?><span class="sale-badge">PROMO</span><?php endif ?>
            </a>
            <div class="product-card-body"><div class="product-card-top"><span class="stock <?= $product['stock']==='En stock'?'in':'order' ?>">● <?= htmlspecialchars($product['stock']) ?></span><span class="product-arrow">↗</span></div><h2><a href="/boutique/<?= rawurlencode($product['slug']) ?>"><?= htmlspecialchars($product['title']) ?></a></h2><p><?= htmlspecialchars(mb_substr($product['description']?:'Équipement professionnel sélectionné et contrôlé par IFMAP.',0,115)) ?></p><footer><div><small>PRIX</small><strong><?= $promo?number_format($product['promotional_price'],0,',',' '):($product['price']?number_format($product['price'],0,',',' '):'Sur demande') ?><?= ($promo||$product['price'])?' FCFA':'' ?></strong><?php if($promo): ?><s><?= number_format($product['price'],0,',',' ') ?> FCFA</s><?php endif ?></div><a class="product-cta" href="/boutique/<?= rawurlencode($product['slug']) ?>" aria-label="Voir <?= htmlspecialchars($product['title']) ?>">Voir le produit <span>→</span></a></footer></div>
        </article><?php endforeach ?>
    </div>
    <div class="shop-empty" data-shop-empty hidden><span>⌕</span><h2>Aucun produit trouvé</h2><p>Modifiez votre recherche, votre budget ou votre catégorie.</p><button class="site-btn primary" type="button" data-reset-products>↺ Réinitialiser les filtres</button></div>
</section>
<script>(()=>{const root=document.querySelector('[data-shop-catalog]');if(!root)return;const grid=root.querySelector('[data-product-grid]'),cards=[...root.querySelectorAll('[data-product-category]')],main=document.querySelector('[data-product-search-main]'),secondary=root.querySelector('[data-product-search-secondary]'),maxPrice=root.querySelector('[data-product-max-price]'),sort=root.querySelector('[data-product-sort]'),buttons=[...root.querySelectorAll('[data-category]')],count=root.querySelector('[data-product-count]'),empty=root.querySelector('[data-shop-empty]');let category='all';const sync=(source,target)=>{source?.addEventListener('input',()=>{if(target&&target.value!==source.value)target.value=source.value;apply()})};const apply=()=>{const q=(main?.value||secondary?.value||'').trim().toLocaleLowerCase(),max=parseInt(maxPrice?.value||'0',10)||0;let visible=[];cards.forEach(card=>{const price=parseInt(card.dataset.productPrice||'0',10)||0;const show=(category==='all'||card.dataset.productCategory===category)&&(!q||card.dataset.productSearchable.includes(q))&&(!max||price===0||price<=max);card.hidden=!show;if(show)visible.push(card)});const mode=sort?.value||'relevance';if(mode!=='relevance'){visible.sort((a,b)=>mode==='name'?a.dataset.productName.localeCompare(b.dataset.productName):mode==='price-asc'?(parseInt(a.dataset.productPrice||'0')||Number.MAX_SAFE_INTEGER)-(parseInt(b.dataset.productPrice||'0')||Number.MAX_SAFE_INTEGER):(parseInt(b.dataset.productPrice||'0')||0)-(parseInt(a.dataset.productPrice||'0')||0));visible.forEach(card=>grid.appendChild(card))}count.textContent=visible.length;empty.hidden=visible.length!==0};sync(main,secondary);sync(secondary,main);maxPrice?.addEventListener('input',apply);sort?.addEventListener('change',apply);buttons.forEach(button=>button.addEventListener('click',()=>{category=button.dataset.category;buttons.forEach(item=>item.classList.toggle('active',item===button));apply()}));root.querySelector('[data-reset-products]')?.addEventListener('click',()=>{category='all';if(main)main.value='';if(secondary)secondary.value='';if(maxPrice)maxPrice.value='';if(sort)sort.value='relevance';buttons.forEach((item,i)=>item.classList.toggle('active',i===0));apply()});document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();main?.focus()}});})();</script>
