<?php
$brand=$_SESSION['brand']??['name'=>'IFMAP','primary'=>'#143f3b','accent'=>'#dc9d2b','logo'=>null,'favicon'=>null];
$brand['favicon']=$brand['favicon']??null;
if(empty($brand['favicon'])){try{$stmt=\App\Core\Database::connection()->prepare("SELECT `value` FROM settings WHERE `group`='branding' AND `key`='favicon' LIMIT 1");$stmt->execute();$brand['favicon']=$stmt->fetchColumn()?:null;}catch(\Throwable){}}
$cartCount=count($_SESSION['cart']??[]);
?>
<!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="<?= htmlspecialchars($brand['name']) ?> — Formation, accompagnement et équipements professionnels en Côte d’Ivoire"><title><?= htmlspecialchars($title) ?> — <?= htmlspecialchars($brand['name']) ?></title><?php if(!empty($brand['favicon'])||!empty($brand['logo'])): ?><link rel="icon" href="<?= htmlspecialchars($brand['favicon']?:$brand['logo']) ?>"><?php endif ?><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Manrope:wght@500;600;700;800&display=swap" rel="stylesheet"><link rel="stylesheet" href="/public/assets/css/app.css"><link rel="stylesheet" href="/public/assets/css/site.css"><link rel="stylesheet" href="/public/assets/css/news.css"><link rel="stylesheet" href="/public/assets/css/branding.css"><style>:root{--site-primary:<?= htmlspecialchars($brand['primary']) ?>;--site-accent:<?= htmlspecialchars($brand['accent']) ?>;--primary:<?= htmlspecialchars($brand['primary']) ?>;--accent:<?= htmlspecialchars($brand['accent']) ?>}</style></head><body class="site-body">
<div class="site-notice"><?= htmlspecialchars($brand['name']) ?>, notre flambeau <span>·</span> Koumassi & Yopougon Niangon — Abidjan <a href="/contact">Besoin d’aide ? Nous contacter</a></div>
<header class="site-header"><a class="site-logo" href="/"><span><?php if(!empty($brand['logo'])): ?><img src="<?= htmlspecialchars($brand['logo']) ?>" alt="Logo <?= htmlspecialchars($brand['name']) ?>"><?php else: ?>IF<?php endif ?></span><strong><?= htmlspecialchars($brand['name']) ?><small>Institut de Formation aux Métiers</small></strong></a><button class="site-menu" data-site-menu>☰</button><nav class="site-nav" id="site-nav"><a class="<?= $active==='home'?'active':'' ?>" href="/">Accueil</a><a class="<?= $active==='trainings'?'active':'' ?>" href="/formations">Formations</a><a class="<?= $active==='shop'?'active':'' ?>" href="/boutique">Boutique</a><a class="<?= $active==='company'?'active':'' ?>" href="/entreprise">Entreprises</a><a href="/academie">Académie en ligne</a><a class="<?= $active==='news'?'active':'' ?>" href="/actualites">Actualités</a><a class="<?= $active==='contact'?'active':'' ?>" href="/contact">Contact</a></nav><div class="site-actions"><?php $accountContext='site';require __DIR__.'/../partials/account-dropdown.php'; ?><a class="cart-link" href="/panier">Panier <b><?= $cartCount ?></b></a></div></header>
<main><?= $content ?></main>
<footer class="site-footer"><div><a class="site-logo light" href="/"><span><?php if(!empty($brand['logo'])): ?><img src="<?= htmlspecialchars($brand['logo']) ?>" alt="Logo <?= htmlspecialchars($brand['name']) ?>"><?php else: ?>IF<?php endif ?></span><strong><?= htmlspecialchars($brand['name']) ?><small>Institut de Formation aux Métiers</small></strong></a><p>Former les compétences, accompagner les entreprises et équiper les professionnels de demain.</p></div><div><h3>Explorer</h3><a href="/entreprise">Solutions entreprises</a><a href="/contact">Contact</a><a href="/formations">Nos formations</a><a href="/academie">Académie en ligne</a><a href="/boutique">Boutique</a></div><div><h3>Informations</h3><a href="/actualites">Actualités</a><a href="/conditions-generales">Conditions générales</a><a href="/retours-remboursements">Retours et remboursements</a></div><div><h3>Nous trouver</h3><p>Base de Koumassi<br>Base de Yopougon Niangon<br>Abidjan, Côte d’Ivoire</p><p>contact@ifmap.ci</p></div><small>© <?= date('Y') ?> <?= htmlspecialchars($brand['name']) ?>. Tous droits réservés.</small></footer><script src="/public/assets/js/app.js"></script></body></html>
